apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: httpd-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: ibmdojo/httpd
		imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
  - name: http
    protocol: TCP
    port: 88
    targetPort: 80
  type: ClusterIP
