apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: httpd-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-container
        image: ibmdojo/httpd
        imagePullPolicy: IfNotPresent
